@startuml
'https://plantuml.com/sequence-diagram

autonumber

--> jdaBuilder: -ingredients
jdaBuilder -->ChefBot: onMessageReceived()
ChefBot --> RecipeBook: getRecipes()
RecipeBook --> CommandBuilder: getClientResponse()
CommandBuilder --> RecipeBook: getJSONArray()

CommandBuilder --> chefBot
Recipe --> CommandBuilder: getJSONObject()
CommandBuilder --> Recipe: jObjectIngredients
RecipeBook --> Recipe: Recipe()
Recipe --> RecipeBook: Recipe Object

CommandBuilder --> RecipeBook: jsonArray
jdaBuilder --> ChefBot: addEventListeners()

@enduml